apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:43UvjnfLZsOHBcAXnHFDhuv8IqlThu+sKYH9STdaZ33XKME0BFYZag==,iv:t1/1lR727NcMBBaSfFK2URNxVaXJTl0sJ5DMLmbc9js=,tag:2bykdmMUvfD+m+jvdQ15TQ==,type:str]
sops:
  age:
    - recipient: age1na5tuux4snund2j7urtz59c72hsjshkt8zmwk4f2sq6ft2533s9sndqaux
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WmpKZ2FuRnlzME5ER1Nq
        WGxnbFNaZnhOdkx3d09tRkt5N29ZRWNicnlvCmV3UkQxb20wakZRSy9ieHh5Ykkw
        ZWdnUDdzNzRNSnViRHkzVGM1bWxIMk0KLS0tIDVTZFlPNWNvZlU4KzFzdS9saHhU
        Tjd6YzJpbGhwSDdPRlUzOXBUVUt6amsK8CRCQ5HB2TZP4uSnoq/T6oSvmhxXIWsb
        FudsiLa3WWhHw8FOgNCZUBqL/ERWCuQFuw5CkngH+1okv8t+MgQX3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:02:48Z"
  mac: ENC[AES256_GCM,data:kXpKs9yrnNN+Y/eTrZ6hdurmD/IDUnxNTXk3i0G1lYrtzI55PpzxDK7C9lmKD9LmeufUTNrzWlrNg52JD4oNbAjIJQ1JOLCvwxQLMwweW4bPBQox5/86d9bSLcPAcciibaJq5iaiMCTpDqmqu4jayXoqaZ5v51tNaj382+S1jm8=,iv:+XvPjst/KB5zqqP5sfhEAEdx+hA/bNdnC+1GyHpxxbs=,tag:vmMyFxdpeoTG5uUQC7J1Nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
