apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:hpHgEAZcQKsLIw==,iv:SOnxxEa9+RL4+BIXl0RGcK4qnDcF775kh2+b0uDDhRc=,tag:iPcajV8LvLlqC89xOHwpdA==,type:str]
sops:
  age:
    - recipient: age1na5tuux4snund2j7urtz59c72hsjshkt8zmwk4f2sq6ft2533s9sndqaux
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT0N6RW9iN2gvUXpkMzZJ
        SmdnVXNDN2JUb01NSG1iYmdFS1BUZW00TVRZCkp0SnRsRGhiZnVmdXNhUzMwQkJH
        V1BiZHpRUUJBTkhtbmhwOVVEZm1sRE0KLS0tIHRSZVRXdzMzcTNRYllLc3Jrdkxv
        REZPLzR6M25MV0RaSnhTMnNQT3BlUWMK9jKxbRYvisjHygSM+hOx74L9PXAvwFvK
        D9A5xkrkCUpooInD1B+69PEm980o75VNqehH0bfSw+BPFb7fFGhVtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:02:48Z"
  mac: ENC[AES256_GCM,data:lKCpL5936lp1ArzYiD2veqc5TKDsDCh2TRaZGeW7xMuShboroui2xi42ew6mtIWNwomRqyjXhryP02bMI2p+airrVypvtVWmx9A/X9g2JINMKKZnOKpPb2JZOsl9pjPzqVwE95mkePsSKDvNGTDp2rzHbKs0kHNGQWVx1zga7RU=,iv:O91hyV7n5GTgTd2S14XIYONcuwFOjx5onQrP/KRllDk=,tag:Z+rtoj+rpFuJ/N+7SMUNZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
