apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qItbuPbCzFBC9oFtVcdPFZ7N7F1XMWorgN20WnO3+0c=,iv:oiv/FhO8s2ZWlkqkSeL5Si7/gZSTzn4wQqOWtKOdDoY=,tag:S8t8xfhCyOPwEXj7lcbxlg==,type:str]
sops:
  age:
    - recipient: age1na5tuux4snund2j7urtz59c72hsjshkt8zmwk4f2sq6ft2533s9sndqaux
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd3VRSW1BM3NqdXk3MlIx
        L3FYeWVtZTBZNlRjcGJQYmFrMXlHOVoyZTNzCjFpZHlNVVVveWRtSE1wVHNFN2Jx
        UmFIVDhtU2MxcnNoTW9Scm9vNWF3dDgKLS0tIDN0UmxVWHpyVDVaMm02NG9zNVEy
        emtMMnhPWCtFTyszRHNBbzN0clp0ajQKU0hh7lcsGs9OCDwwohyOWzZk8lctRb0R
        0j1uQvfN7fyDKBSUaezY2IaUlihW5d3+qxfSUsG2fi0rgNeJD2W/Ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:02:48Z"
  mac: ENC[AES256_GCM,data:00KbpCiVrrgTju7j85BedPcWLmi0KrYcDwyKT45jqRYd8bURw9lVwuId3EkptG6CQiakPvla3/OrxMlWUUFqpoLiTZFgr3032BuvXKiT69oZ95DbPQaTmIYI/ixxAE1RaooPxhqtu89HW1ozzNsuNWFduNVN6wrT2iTilxqd5ZU=,iv:bz0QC3fR8/gxO1zHwXLaiO+hX1VQyGcY9R8jdYl9iqo=,tag:URkBueMcgUzyYRsMq/DXaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
