apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1uk5Cxf7Qb1mWdLsmXj196YEEdueDB5L7i/HlE9aljYe90L6M0BBQlTQ/ELaiY8lqY2/50n3eBNlay8qTKI6AzfXvizYCc9wGZv8MXv06C38+x+jrdhZzUu2XQt9RYSCxMu5mTVVYWkfSPa/nPKGy1xe5o0K8Up1LCymrqDGfrv/i5uAzZj1V+eDR8+6VYTj6aUVl0QPWupPmLHNRVK8prPKNUpo/k4HZv5XNc52hc/6YnhZ,iv:j1SwikCrVdl5pIwn8bX4H4nrHNVpOwwDwJJ3adsoE14=,tag:zlcJlTRrMOPBxVnv8jlCBg==,type:str]
sops:
  age:
    - recipient: age1na5tuux4snund2j7urtz59c72hsjshkt8zmwk4f2sq6ft2533s9sndqaux
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVFZ0UHpUS25oTUtkTHVm
        NVRUbkNFTjdSbUhLTG5mdG9BQjNwZ1RoS0RNCkI5V1h3R1RFekpYR1V6RE1BSFZq
        cHdYRWdicjZqeWxVYkZyY1Q3eDlURDAKLS0tIGVGK0NRVk5KT2hDQk8rbzBHZXIz
        QzY2MTBmSk13VzRmNkMvQ1ZXelF3a1kK1nyAugGxf7Cv8hFvsIid4RXYGGCtaYVO
        klwEd/4bx40xE4jgpkiY7SX6hUZP1Ssd+PSCA6Ev7o4FQF0zA1544g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:02:48Z"
  mac: ENC[AES256_GCM,data:/ynebfQ683vq4fiXrVKSUkxtGAO4C7PyOpnvlYLUZXqox1GLHJq/bqyV3sIX7CQzNFnLJ6aA+MPS7lnscpJA0oB8X5CHoNVmhUO/0vyGrU21wojo9b/J0GBvJ7GDNdnoRODpfUch9vr2tyzm6uotw93BrFuldovQ4+ioyQ7t+bM=,iv:Eq41KJqaYoG3T2Y/BA0zlY2NpjRD+nDmGrzP3JqPm58=,tag:jvlwfHBSgaJU2SrdiNZzBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
